name = "pdisoftware"
main = "services/api-worker/src/index.ts"
compatibility_date = "2024-11-01"
compatibility_flags = ["nodejs_compat"]

[build]
command = "pnpm --filter web build"

[assets]
directory = "./apps/web/dist"
binding = "ASSETS"
not_found_handling = "single-page-application"

[vars]
ENVIRONMENT = "production"
SUPABASE_URL = "https://ckwzbaazgbheeeuclbci.supabase.co"
SUPABASE_ANON_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImNrd3piYWF6Z2JoZWVldWNsYmNpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3ODkyNzQzMTYsImV4cCI6MjEwNDg1MDMxNn0.uv_oLFH_uybZJEYZ3x_-OfT3g_7vPBmbmwk5HTUdpqI"

